name: Dont Run on Draft PR
author: zx.cs@qq.com
description: This action will fail if the PR is a draft.
branding:
  icon: skip-forward
  color: green

runs:
  using: composite
  steps:
    - run: |
        if [ "${{ github.event.pull_request.draft }}" = "true" ]; then
          echo "This is a draft PR. Now exiting..."
          exit 1
        fi
        exit 0
      shell: bash
