name: Test Myself

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

  workflow_dispatch:

jobs:
  dont-run-on-draft-pr:
    name: Don't Run on Draft PR
    runs-on: ubuntu-latest
    steps:
      - uses: z0gSh1u/dont-run-on-draft-pr@v1.0.0

  whatever-else:
    needs: dont-run-on-draft-pr
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
